environment:
    matrix:
        - nodejs_version: "0.12"
        - nodejs_version: "4.0"
        - nodejs_version: "5.0"
        - nodejs_version: "6.0"
        - nodejs_version: "7.0"

install:
    - git submodule update --init --recursive
    - npm -g install npm@next
    - npm install

test_script:
    - node --version
    - npm --version
    - npm test

build: off
