environment:
    matrix:
        - GENERATOR: "Visual Studio 14"
          CONFIG: Release
        - nodejs_version: "0.12"
        - nodejs_version: "4.0"
install:
    - npm install
test_script:
    - node --version
    - npm --version
    - npm test